__title__ = 'secret_service_scripts'
__description__ = 'List password entries, search for username, get username and password using Secret Service API'
__url__ = 'https://github.com/johanwiden/secret-service-scripts'
__version__ = '0.1.0'
__author__ = 'Johan Widén'
__author_email__ = 'j.e.widen@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 Johan Widén'
