#!/usr/bin/env python3
# https://stackoverflow.com/questions/72020628/how-do-i-list-and-access-the-secrets-stored-in-ubuntus-keyring-from-the-command
# In ubuntu: sudo apt get python3-secretstorage
#
# Return password for password entry with name given by first argument.

import argparse
import secretstorage

parser = argparse.ArgumentParser(
    prog = 'keyring-show-password',
    description = 'Return password for password entry password_name')
parser.add_argument('password_name', type=str)
args = parser.parse_args()

conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
for item in collection.get_all_items():
    attributes = item.get_attributes()
    if 'service' in attributes and attributes['service'] == args.password_name:
        print(item.get_secret().decode('utf-8'))
        break
