#!/usr/bin/env python3
# https://stackoverflow.com/questions/72020628/how-do-i-list-and-access-the-secrets-stored-in-ubuntus-keyring-from-the-command
# In ubuntu: sudo apt get python3-secretstorage

import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
services = []
for item in collection.get_all_items():
    attributes = item.get_attributes()
    if 'service' in attributes:
        services.append(attributes['service'])
print(' '.join(e for e in sorted(set(services))))
